// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// irls_fit_cpp
List irls_fit_cpp(const arma::mat& X, const arma::vec& y, int family_id, int link_id, int maxit, double tol);
RcppExport SEXP _panglm_irls_fit_cpp(SEXP XSEXP, SEXP ySEXP, SEXP family_idSEXP, SEXP link_idSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type family_id(family_idSEXP);
    Rcpp::traits::input_parameter< int >::type link_id(link_idSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(irls_fit_cpp(X, y, family_id, link_id, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// random_binomial_loglik_grad_cpp
List random_binomial_loglik_grad_cpp(const arma::vec& beta, double sigma, const arma::mat& X, const arma::vec& y, IntegerVector group_start, IntegerVector group_size, NumericVector nodes, NumericVector weights, int link_id);
RcppExport SEXP _panglm_random_binomial_loglik_grad_cpp(SEXP betaSEXP, SEXP sigmaSEXP, SEXP XSEXP, SEXP ySEXP, SEXP group_startSEXP, SEXP group_sizeSEXP, SEXP nodesSEXP, SEXP weightsSEXP, SEXP link_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_size(group_sizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nodes(nodesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type link_id(link_idSEXP);
    rcpp_result_gen = Rcpp::wrap(random_binomial_loglik_grad_cpp(beta, sigma, X, y, group_start, group_size, nodes, weights, link_id));
    return rcpp_result_gen;
END_RCPP
}
// group_means_cpp
List group_means_cpp(NumericMatrix X, NumericVector y, IntegerVector group_start, IntegerVector group_size);
RcppExport SEXP _panglm_group_means_cpp(SEXP XSEXP, SEXP ySEXP, SEXP group_startSEXP, SEXP group_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_size(group_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(group_means_cpp(X, y, group_start, group_size));
    return rcpp_result_gen;
END_RCPP
}
// quasi_demean_cpp
List quasi_demean_cpp(NumericMatrix X, NumericVector y, IntegerVector group_start, IntegerVector group_size, NumericVector theta);
RcppExport SEXP _panglm_quasi_demean_cpp(SEXP XSEXP, SEXP ySEXP, SEXP group_startSEXP, SEXP group_sizeSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_size(group_sizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(quasi_demean_cpp(X, y, group_start, group_size, theta));
    return rcpp_result_gen;
END_RCPP
}
// random_poisson_fit_cpp
List random_poisson_fit_cpp(const arma::mat& X, const arma::vec& y, IntegerVector group_start, IntegerVector group_size, int maxit, double tol);
RcppExport SEXP _panglm_random_poisson_fit_cpp(SEXP XSEXP, SEXP ySEXP, SEXP group_startSEXP, SEXP group_sizeSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_size(group_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(random_poisson_fit_cpp(X, y, group_start, group_size, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// within_demean_cpp
List within_demean_cpp(NumericMatrix X, NumericVector y, IntegerVector group_start, IntegerVector group_size);
RcppExport SEXP _panglm_within_demean_cpp(SEXP XSEXP, SEXP ySEXP, SEXP group_startSEXP, SEXP group_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_size(group_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(within_demean_cpp(X, y, group_start, group_size));
    return rcpp_result_gen;
END_RCPP
}
// within_poisson_fit_cpp
List within_poisson_fit_cpp(const arma::mat& X, const arma::vec& y, IntegerVector group_start, IntegerVector group_size, int maxit, double tol);
RcppExport SEXP _panglm_within_poisson_fit_cpp(SEXP XSEXP, SEXP ySEXP, SEXP group_startSEXP, SEXP group_sizeSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_start(group_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_size(group_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(within_poisson_fit_cpp(X, y, group_start, group_size, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_panglm_irls_fit_cpp", (DL_FUNC) &_panglm_irls_fit_cpp, 6},
    {"_panglm_random_binomial_loglik_grad_cpp", (DL_FUNC) &_panglm_random_binomial_loglik_grad_cpp, 9},
    {"_panglm_group_means_cpp", (DL_FUNC) &_panglm_group_means_cpp, 4},
    {"_panglm_quasi_demean_cpp", (DL_FUNC) &_panglm_quasi_demean_cpp, 5},
    {"_panglm_random_poisson_fit_cpp", (DL_FUNC) &_panglm_random_poisson_fit_cpp, 6},
    {"_panglm_within_demean_cpp", (DL_FUNC) &_panglm_within_demean_cpp, 4},
    {"_panglm_within_poisson_fit_cpp", (DL_FUNC) &_panglm_within_poisson_fit_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_panglm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
